name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: centos-latest
    steps:
      - name: Deploy Ruby App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP Address of the server you wish to ssh into.
          key: ${{secrets.SSH_KEY}} # Private key to your server.
          username: ${{secrets.SSH_USERNAME}} # User of the server you wish to login to.

          script: |
            mkdir krowdwallet #create directory you want to deploy to in the live server.
            cd krowdwallet #cd into app directory.
            git clone git@github.com:shanealton/krowdwalletdocs.git #clone the repo into the directory.
            echo 'Deployment successful to Digital Ocean Droplet!' #message to be displayed after successful deployment.
