name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Ruby App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP Address of the server you wish to ssh into.
          key: ${{secrets.SSH_KEY}} # Private key to your server.
          username: ${{secrets.SSH_USERNAME}} # User of the server you wish to login to.

          script: |
            cd krowd/krowdwalletdocs
            git pull --ff-only
            echo 'Deployment successful to Digital Ocean Droplet!'
